fix pip install error
fix pip install
```
INFO: pip is looking at multiple versions of asteroid to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r .\requirements.txt (line 10), -r .\requirements.txt (line 12), -r .\requirements.txt (line 27), -r .\requirements.txt (line 41), -r .\requirements.txt (line 45), -r .\requirements.txt (line 49), -r .\requirements.txt (line 52) and scipy==1.9.3 because these package versions have con
flicting dependencies.

The conflict is caused by:
    The user requested scipy==1.9.3
    librosa 0.9.2 depends on scipy>=1.2.0
    matchering 2.0.6 depends on scipy>=1.9.2
    soundstretch 1.2 depends on scipy
    dora 0.0.3 depends on scipy>=0.17.0
    audiomentations 0.24.0 depends on scipy<2 and >=1.0.0
    spafe 0.3.2 depends on scipy>=1.7.3
    asteroid 0.7.0 depends on scipy>=1.10.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```